### ISSUE TITLE
Enabling directly used in Azure function 

### ISSUE THREAD

**Issue by manan0kansara** [KyleJamesWalker/telebot#12]
I have show your project that interenlly used telegram api Right ???

1. Make it enable to work in azure function in http trigger event.

**This work enable directly used this library in azure function tha attract lot's of attraction.
I am using this to make my trade order automatically with my broker this feature add more money to all user pocket who make trading with telegram command**

**Comment by KyleJamesWalker** [comment]
I'm assuming you're using https://github.com/eternnoir/pyTelegramBotAPI and not this package.
