### ISSUE TITLE
Still in support?

### ISSUE THREAD

**Issue by dmtzs** [KyleJamesWalker/telebot#8]
I just wan to ask if this library is still with support? Because I see that there are some methods that are not implemented yet inside ``__init__.py`` file, I can be ineterested to implement the rest of the functionality so my main question is that how can be the metodology from my part to contribute in this project?

**Comment by KyleJamesWalker** [comment]
I still use it for a few bot's that I have running, but I haven't done much work on it, so it's pretty out of date for sure.

When I wrote this I couldn't find any other frameworks out there, but now I think there are quite a few like: https://pypi.org/project/pyTelegramBotAPI/ so it might be worth checking others out, or always feel free to submit a PR to add features. 🙃
