### ISSUE TITLE
Please rename lib

### ISSUE THREAD

**Issue by Vasiliy566** [KyleJamesWalker/telebot#9]
Most popular lib for telegram bots - https://pypi.org/project/pyTelegramBotAPI have some troubles beac of your package.
If you try to write there example in Pycharm:
```
import telebot

bot = telebot.TeleBot("TOKEN", parse_mode=None) # You can set parse_mode by default. HTML or MARKDOWN
```
and press on `import telebot` that underline with red and choose install telebot - it install wrong lib that is your lib
many python developers - beginner handle with that bug and do not know what to do.

**Comment by KyleJamesWalker** [comment]
Yes I know. I would to work with the maintainer of the library to do anything with this.

Otherwise I would make it worse by giving a bad actor a chance to add malicious code for all those people.
